version: '2'
services:
  odoo:
    image: odoo:9
    container_name: odoov9
    depends_on:
      - db
    ports:
      - "8104:8069"
    volumes:
      - ./odoo:/var/lib/odoo
      #- ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    restart: always
    environment:
     - DB_PORT_5432_TCP_ADDR=db
     - DB_PORT_5432_TCP_PORT=5432
     - DB_ENV_POSTGRES_USER=odoo
     - DB_ENV_POSTGRES_PASSWORD=odoo
  db:
    image: postgres:9.5
    container_name: db9.5
    ports:
      - "5448:5432"
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - ./data:/var/lib/postgresql/data/
    restart: always
